### ISSUE TITLE
Écrire un base pour UIElement et Button

### ISSUE THREAD

**Issue by AdlarX9** [Equinoxs/trophees-nsi#6]
Il faut commencer à écrire notre système de menu (`Menu` est inclus dedans), voir avec Guillaume pour utiliser sa bibliothèque PGMenu, je pense que ça vaut le coup. Il sera donc nécessaire de trouver un moyen pour nos `Button` (pas les `UIElement` du coup) d'agir, d'avoir une fonction dans le jeu. Pour l'instant, on n'a pas besoin que ça soit trop complexe pour les utiliser. Si c'est nécessaire, on pourra stocker toutes les informations nécessaires à nos `Button` dans des fichiers JSON, pour alléger le code (ceci est une simple réflexion, à tout moment ça rend les choses moins logiques et/ou ça alourdit le code).

**Comment by Dim-Bananox** [comment]
J'ai commencé à coder ui_element et button, il faudra que je rajoute d'autres trucs mais l'essentiel est là

**Comment by AdlarX9** [comment]
**C'est très bien** que tu prennes enfin part au projet. Si on parle code, t'as réécrit la logique de `GameLoop` (la boucle principal) dans ton fichier, et tu n'as pas écrit `UIElement`, parent de `Button` (rappel toi ce qu'il y a sur le Canva.

Point supplémentaire : en POO, **on évite à tout prix** de faire des fonctions toutes seules comme tu l'as fait. Tu as écrit la class `Menu` (qui est assez bien faite) dans le fichier de `UIElement` alors qu'il aurait du être dans `menu/main.py` (qui n'est pas encore créé je crois).

**Si tu veux afficher à l'écran du concret**, il te faudra des données. Pour se faire,  tu peux créer un nouveau fichier `ui_element/data.json` qui stockera toutes les infos sur tes `UIElement`.
Ensuite, il faudra que tu **ajoutes une méthode** dans `DataHandler` pour récupérer ces informations.

Du côté des fonctions que tu as déjà faites (mettre en pause le jeu, etc), comme chaque `Button` a sa propre action, tu peux créer un fichier `button/actions.py` qui stocke ces fonctions avec **la même logique** que dans `src/utils/interactions.py` (il faudra également que tu modifie `DataHandler` pour récupérer ces fonctions).
Ces fonctions devront bien sûr traiter avec les méthodes des autres classes et ne pas faire cavaliers seuls en réécrivant la roue !

Pour **initialiser** tes `UIElement` et les **afficher**, il serait judicieux de créer un singleton `MenuHandler` qui enregistrerait tous les `Menu` possibles et inimaginables dès **l'initialisation du jeu** (cette class est plus compliquée à faire), il fournirait une méthode `render()` qui serait appelée par `Camera`.

Enfin, la manière dont tu parlais me laisse entendre que tu exécutait le programme en prenant `ui_element/main.py` comme point d'entrée. Mais il est fait pour être exécuter depuis `sources/main.py` (exemple : `python "/path/to/trophees-nsi/sources/main.py"` au lieu de faire `python "/path/to/classes/basics/ui_element/main.py"`).

J'espère que j'ai été assez clair, et n'hésite pas à me solliciter pour de l'aide !
